### ISSUE TITLE
Poloniex Callback Error

### ISSUE THREAD

**Issue by anazhd** [rafaelcmrj/bot-btc-poloniex#5]
Bought xmr perfectly, but did not sell back after x% increase. it will continue on making another buy.
take a look

> === PRICE INFORMATION ===
> base price: 0.02131992
> price target to buy: 0.02110672
> 
> **\* POLONIEX CALLBACK ***
> { orderNumber: '34258042779', resultingTrades: [] }
> ---
> 
> === ORDER INFORMATION ===
> type: BUY
> price: 0.02103007
> target to sell: 0.02124037
> security margin: 0.02089352
> 
> **\* POLONIEX CALLBACK ***
> Nonce must be greater than 1473448439625001. You provided 1473448439413001.
> ---
> 
> **\* POLONIEX CALLBACK ***
> Nonce must be greater than 1473448466603001. You provided 1473448466102001.
> ---
> 
> === PRICE INFORMATION ===
> base price: 0.02110000
> price target to buy: 0.02088900

**Comment by rafaelcmrj** [comment]
@anazhd I'm working on it now, I will push a new version tonight with it fixed.

**Comment by anazhd** [comment]
@rafaelcmrj alright cool :)

**Comment by rafaelcmrj** [comment]
@anazhd we still getting the error from Poloniex API but it isn't affecting the bot (I'm keeping it on log just to know when it happens). Bot is working fine now, placing orders to buy and sell. Have fun!
